### PR TITLE
Proposal: Don't override Ruby's core method

### PR DESCRIPTION
**Pull request by eagletmt**
Rename Client#send to Client#send_data

### CODE REVIEW

**Comment by abrandoned** [comment]
:+1:

**Comment by shokai** [comment]
`Object#send` (used for metaprogramming) can do the same for `Object#__ send__`.
So I think overwriting `send` is no problem.

**Comment by eagletmt** [comment]
I know `Object#__send__`, but most Ruby programmers and libraries expect `#send` acts like `#__send__`.
I think any methods should not be overridden unless it's intentional (such as overriding `#to_s` or `#==` ).

**Comment by shokai** [comment]
I do not know why default method should not be overwritten.
Most programmers do not know `#send`, and high-level programmers they want to use `#send` can read documents.

and, Why `#__send__` exists? I think that send is assumed to be overwritten because it is a common name.

**Comment by eagletmt** [comment]
It turned out that my thoughts and yours are completely different. Closing this proposal.

**Pull request closed without merging**
